export default {
	// name: 'department',
	icon: 'icon-Department',
	path: '/department',
	routes: [
		{
			exact: true,
			path: '/department',
			redirect: '/department/Inbound_processing',
		},
		// {
		//   // name: 'manual_request',
		//   icon: null,
		//   path: '/department/manual_request',
		//   access: 'warehouse_request_apply_list',
		//   routes: [
		//     {
		//       exact: true,
		//       // name: 'manual_request_list',
		//       path: '/department/manual_request',
		//       access: 'warehouse_request_apply_list',
		//       component: './department/manual_request/list/index.tsx',
		//     },
		//     {
		//       exact: true,
		//       // name: 'manual_request_add',
		//       path: '/department/manual_request/add',
		//       access: 'warehouse_request_add_apply',
		//       component: './department/manual_request/add/index.tsx',
		//     },
		//     {
		//       exact: true,
		//       // name: 'manual_request_edit',
		//       path: '/department/manual_request/edit/:id/:warehouseId',
		//       access: 'warehouse_request_edit',
		//       component: './department/manual_request/add/index.tsx',
		//     },
		//     {
		//       exact: true,
		//       // name: 'manual_request_list',
		//       path: '/department/manual_request/:id/:readOnly',
		//       access: 'warehouse_request_apply_list',
		//       component: './department/manual_request/list/',
		//     },
		//     {
		//       exact: true,
		//       // name: 'manual_request_list',
		//       path: '/department/manual_request/:id/:readOnly/:messageType',
		//       access: 'warehouse_request_apply_list',
		//       component: './department/manual_request/list',
		//     },
		//     { component: '404' },
		//   ],
		// },
		// {
		//   // name: 'operation_request',
		//   icon: null,
		//   path: '/department/operation_request',
		//   access: 'surgical_package_request_list',
		//   routes: [
		//     {
		//       exact: true,
		//       // name: 'operation_request_list',
		//       path: '/department/operation_request',
		//       access: 'surgical_package_request_list',
		//       component: './department/operation_request',
		//     },
		//     {
		//       exact: true,
		//       // name: 'operation_request_add',
		//       path: '/department/operation_request/add/:id',
		//       access: 'add_surgical_package_request',
		//       component: './department/operation_request/add',
		//     },
		//     {
		//       exact: true,
		//       // name: 'operation_request_list',
		//       path: '/department/operation_request/:id/:readOnly',
		//       access: 'surgical_package_request_list',
		//       component: './department/operation_request',
		//     },
		//   ],
		// },
		{
			// name: 'Inbound_processing',
			path: '/department/Inbound_processing',
			icon: null,
			access: 'Inbound_processing',
			routes: [
				{
					exact: true,
					// name: 'Inbound_processing',
					path: '/department/Inbound_processing',
					access: 'Inbound_processing',
					component: './department/Inbound_processing',
					wrappers: ['@/wrappers/todoList/inboundProcessingSelect'],
				},
				{
					exact: true,
					path: '/department/Inbound_processing/:id/:readOnly',
					access: 'Inbound_processing',
					component: './department/Inbound_processing',
				},
				{ component: '404' },
			],
		},
		{
			// name: 'warehouse_queries',
			path: '/department/warehouse_queries',
			icon: null,
			access: 'warehouse_queries',
			routes: [
				{
					exact: true,
					// name: 'warehouse_queries',
					path: '/department/warehouse_queries',
					access: 'warehouse_queries',
					component: './department/warehouse_queries',
				},
				{
					exact: true,
					path: '/department/warehouse_queries/:id/:readOnly',
					access: 'warehouse_queries',
					component: './department/warehouse_queries',
				},
				{ component: '404' },
			],
		},
		// {
		//   // name: 'surgical_receiving',
		//   icon: null,
		//   path: '/department/surgical_receiving',
		//   component: './department/surgical_receiving',
		//   access: 'surgical_receiving_list',
		// },
		{
			// name: 'warehousing_apply',
			icon: null,
			path: '/department/warehousing_apply',
			component: './department/warehousing_apply/list',
			access: 'warehousing_apply',
			wrappers: ['@/wrappers/todoList/warehousingApplySelect'],
		},
		{
			// name: 'warehousing_apply_add',
			path: '/department/warehousing_apply/add',
			access: 'warehouse_request_add_apply',
			component: './department/warehousing_apply/add',
		},
		{
			exact: true,
			// name: 'warehousing_apply_edit',
			path: '/department/warehousing_apply/edit/:id/:warehouseId/:sourceWarehouseId',
			access: 'warehousing_apply_edit',
			component: './department/warehousing_apply/add',
		},
		{
			exact: true,
			// name: 'warehousing_apply',
			path: '/department/warehousing_apply/:id/:readOnly',
			access: 'warehousing_apply',
			component: './department/warehousing_apply/list',
		},
		{
			exact: true,
			// name: 'warehousing_apply',
			path: '/department/warehousing_apply/:id/:readOnly/:messageType',
			access: 'warehousing_apply',
			component: './department/warehousing_apply/list',
		},
		// {
		//   // name: 'reallocation',
		//   icon: null,
		//   path: '/department/reallocation',
		//   access: 'reallocation_list',
		//   routes: [
		//     {
		//       exact: true,
		//       // name: 'reallocation_list',
		//       path: '/department/reallocation',
		//       access: 'warehouse_request_view',
		//       component: './department/reallocation/list',
		//     },
		//     {
		//       exact: true,
		//       // name: 'reallocation_list',
		//       path: '/department/reallocation/:id/:readOnly',
		//       access: 'warehouse_request_view',
		//       component: './department/reallocation/list',
		//     },
		//     {
		//       exact: true,
		//       // name: 'reallocation_add',
		//       path: '/department/reallocation/add',
		//       access: 'warehouse_request_add_apply',
		//       component: './department/reallocation/add',
		//     },
		//     {
		//       component: '404',
		//     },
		//   ],
		// },
		{
			// name: 'return_processing',
			icon: null,
			path: '/department/return_processing',
			access: 'return_processing',
			routes: [
				{
					exact: true,
					// name: 'return_processing',
					path: '/department/return_processing',
					access: 'return_processing',
					component: './department/return_processing',
					wrappers: ['@/wrappers/todoList/returnProcessingSelect'],
				},
				{
					exact: true,
					// name: 'return_processing',
					path: '/department/return_processing/:id/:readOnly',
					access: 'return_processing',
					component: './department/return_processing',
				},
				{
					exact: true,
					// name: 'return_purchase_department_add',
					path: '/department/return_processing/return_purchase_department_add',
					access: 'department_add_return_goods',
					component: './department/return_purchase_department/add',
				},
				{
					exact: true,
					// name: 'return_purchase_add',
					path: '/department/return_processing/return_purchase_add',
					access: 'add_return_goods',
					component: './repository/return_purchase/add',
				},
				{
					component: '404',
				},
			],
		},
		{
			// name: 'return_query',
			icon: null,
			path: '/department/return_query',
			access: 'return_query',
			routes: [
				{
					exact: true,
					// name: 'return_query',
					path: '/department/return_query',
					access: 'return_query',
					component: './department/return_query',
				},
				{
					exact: true,
					// name: 'return_query',
					path: '/department/return_query/:id/:readOnly',
					access: 'return_query',
					component: './department/return_query',
				},
				{
					component: '404',
				},
			],
		},
		// {
		//   // name: 'pleaseGet_inquire',
		//   icon: null,
		//   path: '/department/pleaseGet_inquire',
		//   access: 'department_pleaseGet_inquire_list',
		//   routes: [
		//     {
		//       exact: true,
		//       path: '/department/pleaseGet_inquire',
		//       // name: 'pleaseGet_inquire_list',
		//       access: 'department_pleaseGet_inquire_list',
		//       component: './department/pleaseGet_inquire',
		//     },
		//     {
		//       component: '404',
		//     },
		//   ],
		// },
		// {
		//   // name: 'dueIn_goodsAndMaterials',
		//   icon: null,
		//   path: '/department/dueIn_goodsAndMaterials',
		//   access: 'dueIn_goodsAndMaterials_list',
		//   routes: [
		//     {
		//       exact: true,
		//       // name: 'dueIn_goodsAndMaterials',
		//       path: '/department/dueIn_goodsAndMaterials',
		//       access: 'dueIn_goodsAndMaterials_list',
		//       component: './department/dueIn_goodsAndMaterials',
		//     },
		//     {
		//       component: '404',
		//     },
		//   ],
		// },
		{
			component: '404',
		},
	],
};
